export default [
  {city: "aberdeen"},
  {city: "abilene"},
  {city: "akron"},
  {city: "albany"},
  {city: "albuquerque"},
  {city: "alexandria"},
  {city: "allentown"},
  {city: "amarillo"},
  {city: "anaheim"},
  {city: "anchorage"},
  {city: "ann arbor"},
  {city: "antioch"},
  {city: "apple valley"},
  {city: "appleton"},
  {city: "arlington"},
  {city: "arvada"},
  {city: "asheville"},
  {city: "athens"},
  {city: "atlanta"},
  {city: "atlantic city"},
  {city: "augusta"},
  {city: "aurora"},
  {city: "austin"},
  {city: "bakersfield"},
  {city: "baltimore"},
  {city: "barnstable"},
  {city: "baton rouge"},
  {city: "beaumont"},
  {city: "bel air"},
  {city: "bellevue"},
  {city: "berkeley"},
  {city: "bethlehem"},
  {city: "billings"},
  {city: "birmingham"},
  {city: "bloomington"},
  {city: "boise"},
  {city: "boise city"},
  {city: "bonita springs"},
  {city: "boston"},
  {city: "boulder"},
  {city: "bradenton"},
  {city: "bremerton"},
  {city: "bridgeport"},
  {city: "brighton"},
  {city: "brownsville"},
  {city: "bryan"},
  {city: "buffalo"},
  {city: "burbank"},
  {city: "burlington"},
  {city: "cambridge"},
  {city: "canton"},
  {city: "cape coral"},
  {city: "carrollton"},
  {city: "cary"},
  {city: "cathedral city"},
  {city: "cedar rapids"},
  {city: "champaign"},
  {city: "chandler"},
  {city: "charleston"},
  {city: "charlotte"},
  {city: "chattanooga"},
  {city: "chesapeake"},
  {city: "chicago"},
  {city: "chula vista"},
  {city: "cincinnati"},
  {city: "clarke county"},
  {city: "clarksville"},
  {city: "clearwater"},
  {city: "cleveland"},
  {city: "college station"},
  {city: "colorado springs"},
  {city: "columbia"},
  {city: "columbus"},
  {city: "concord"},
  {city: "coral springs"},
  {city: "corona"},
  {city: "corpus christi"},
  {city: "costa mesa"},
  {city: "dallas"},
  {city: "daly city"},
  {city: "danbury"},
  {city: "davenport"},
  {city: "davidson county"},
  {city: "dayton"},
  {city: "daytona beach"},
  {city: "deltona"},
  {city: "denton"},
  {city: "denver"},
  {city: "des moines"},
  {city: "detroit"},
  {city: "downey"},
  {city: "duluth"},
  {city: "durham"},
  {city: "el monte"},
  {city: "el paso"},
  {city: "elizabeth"},
  {city: "elk grove"},
  {city: "elkhart"},
  {city: "erie"},
  {city: "escondido"},
  {city: "eugene"},
  {city: "evansville"},
  {city: "fairfield"},
  {city: "fargo"},
  {city: "fayetteville"},
  {city: "fitchburg"},
  {city: "flint"},
  {city: "fontana"},
  {city: "fort collins"},
  {city: "fort lauderdale"},
  {city: "fort smith"},
  {city: "fort walton beach"},
  {city: "fort wayne"},
  {city: "fort worth"},
  {city: "frederick"},
  {city: "fremont"},
  {city: "fresno"},
  {city: "fullerton"},
  {city: "gainesville"},
  {city: "garden grove"},
  {city: "garland"},
  {city: "gastonia"},
  {city: "gilbert"},
  {city: "glendale"},
  {city: "grand prairie"},
  {city: "grand rapids"},
  {city: "grayslake"},
  {city: "green bay"},
  {city: "greenbay"},
  {city: "greensboro"},
  {city: "greenville"},
  {city: "gulfport-biloxi"},
  {city: "hagerstown"},
  {city: "hampton"},
  {city: "harlingen"},
  {city: "harrisburg"},
  {city: "hartford"},
  {city: "havre de grace"},
  {city: "hayward"},
  {city: "hemet"},
  {city: "henderson"},
  {city: "hesperia"},
  {city: "hialeah"},
  {city: "hickory"},
  {city: "high point"},
  {city: "hollywood"},
  {city: "honolulu"},
  {city: "houma"},
  {city: "houston"},
  {city: "howell"},
  {city: "huntington"},
  {city: "huntington beach"},
  {city: "huntsville"},
  {city: "independence"},
  {city: "indianapolis"},
  {city: "inglewood"},
  {city: "irvine"},
  {city: "irving"},
  {city: "jackson"},
  {city: "jacksonville"},
  {city: "jefferson"},
  {city: "jersey city"},
  {city: "johnson city"},
  {city: "joliet"},
  {city: "kailua"},
  {city: "kalamazoo"},
  {city: "kaneohe"},
  {city: "kansas city"},
  {city: "kennewick"},
  {city: "kenosha"},
  {city: "killeen"},
  {city: "kissimmee"},
  {city: "knoxville"},
  {city: "lacey"},
  {city: "lafayette"},
  {city: "lake charles"},
  {city: "lakeland"},
  {city: "lakewood"},
  {city: "lancaster"},
  {city: "lansing"},
  {city: "laredo"},
  {city: "las cruces"},
  {city: "las vegas"},
  {city: "layton"},
  {city: "leominster"},
  {city: "lewisville"},
  {city: "lexington"},
  {city: "lincoln"},
  {city: "little rock"},
  {city: "long beach"},
  {city: "lorain"},
  {city: "los angeles"},
  {city: "louisville"},
  {city: "lowell"},
  {city: "lubbock"},
  {city: "macon"},
  {city: "madison"},
  {city: "manchester"},
  {city: "marina"},
  {city: "marysville"},
  {city: "mcallen"},
  {city: "mchenry"},
  {city: "medford"},
  {city: "melbourne"},
  {city: "memphis"},
  {city: "merced"},
  {city: "mesa"},
  {city: "mesquite"},
  {city: "miami"},
  {city: "milwaukee"},
  {city: "minneapolis"},
  {city: "miramar"},
  {city: "mission viejo"},
  {city: "mobile"},
  {city: "modesto"},
  {city: "monroe"},
  {city: "monterey"},
  {city: "montgomery"},
  {city: "moreno valley"},
  {city: "murfreesboro"},
  {city: "murrieta"},
  {city: "muskegon"},
  {city: "myrtle beach"},
  {city: "naperville"},
  {city: "naples"},
  {city: "nashua"},
  {city: "nashville"},
  {city: "new bedford"},
  {city: "new haven"},
  {city: "new london"},
  {city: "new orleans"},
  {city: "new york"},
  {city: "new york city"},
  {city: "newark"},
  {city: "newburgh"},
  {city: "newport news"},
  {city: "norfolk"},
  {city: "normal"},
  {city: "norman"},
  {city: "north charleston"},
  {city: "north las vegas"},
  {city: "north port"},
  {city: "norwalk"},
  {city: "norwich"},
  {city: "oakland"},
  {city: "ocala"},
  {city: "oceanside"},
  {city: "odessa"},
  {city: "ogden"},
  {city: "oklahoma city"},
  {city: "olathe"},
  {city: "olympia"},
  {city: "omaha"},
  {city: "ontario"},
  {city: "orange"},
  {city: "orem"},
  {city: "orlando"},
  {city: "overland park"},
  {city: "oxnard"},
  {city: "palm bay"},
  {city: "palm springs"},
  {city: "palmdale"},
  {city: "panama city"},
  {city: "pasadena"},
  {city: "paterson"},
  {city: "pembroke pines"},
  {city: "pensacola"},
  {city: "peoria"},
  {city: "philadelphia"},
  {city: "phoenix"},
  {city: "pittsburgh"},
  {city: "plano"},
  {city: "pomona"},
  {city: "pompano beach"},
  {city: "port arthur"},
  {city: "port orange"},
  {city: "port saint lucie"},
  {city: "port st. lucie"},
  {city: "portland"},
  {city: "portsmouth"},
  {city: "poughkeepsie"},
  {city: "providence"},
  {city: "provo"},
  {city: "pueblo"},
  {city: "punta gorda"},
  {city: "racine"},
  {city: "raleigh"},
  {city: "rancho cucamonga"},
  {city: "reading"},
  {city: "redding"},
  {city: "reno"},
  {city: "richland"},
  {city: "richmond"},
  {city: "richmond county"},
  {city: "riverside"},
  {city: "roanoke"},
  {city: "rochester"},
  {city: "rockford"},
  {city: "roseville"},
  {city: "round lake beach"},
  {city: "sacramento"},
  {city: "saginaw"},
  {city: "saint louis"},
  {city: "saint paul"},
  {city: "saint petersburg"},
  {city: "salem"},
  {city: "salinas"},
  {city: "salt lake city"},
  {city: "san antonio"},
  {city: "san bernardino"},
  {city: "san buenaventura"},
  {city: "san diego"},
  {city: "san francisco"},
  {city: "san jose"},
  {city: "santa ana"},
  {city: "santa barbara"},
  {city: "santa clara"},
  {city: "santa clarita"},
  {city: "santa cruz"},
  {city: "santa maria"},
  {city: "santa rosa"},
  {city: "sarasota"},
  {city: "savannah"},
  {city: "scottsdale"},
  {city: "scranton"},
  {city: "seaside"},
  {city: "seattle"},
  {city: "sebastian"},
  {city: "shreveport"},
  {city: "simi valley"},
  {city: "sioux city"},
  {city: "sioux falls"},
  {city: "south bend"},
  {city: "south lyon"},
  {city: "spartanburg"},
  {city: "spokane"},
  {city: "springdale"},
  {city: "springfield"},
  {city: "st. louis"},
  {city: "st. paul"},
  {city: "st. petersburg"},
  {city: "stamford"},
  {city: "sterling heights"},
  {city: "stockton"},
  {city: "sunnyvale"},
  {city: "syracuse"},
  {city: "tacoma"},
  {city: "tallahassee"},
  {city: "tampa"},
  {city: "temecula"},
  {city: "tempe"},
  {city: "thornton"},
  {city: "thousand oaks"},
  {city: "toledo"},
  {city: "topeka"},
  {city: "torrance"},
  {city: "trenton"},
  {city: "tucson"},
  {city: "tulsa"},
  {city: "tuscaloosa"},
  {city: "tyler"},
  {city: "utica"},
  {city: "vallejo"},
  {city: "vancouver"},
  {city: "vero beach"},
  {city: "victorville"},
  {city: "virginia beach"},
  {city: "visalia"},
  {city: "waco"},
  {city: "warren"},
  {city: "washington"},
  {city: "waterbury"},
  {city: "waterloo"},
  {city: "west covina"},
  {city: "west valley city"},
  {city: "westminster"},
  {city: "wichita"},
  {city: "wilmington"},
  {city: "winston"},
  {city: "winter haven"},
  {city: "worcester"},
  {city: "yakima"},
  {city: "yonkers"},
  {city: "york"},
  {city: "youngstown"}
];